/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appfloristeria;
import Controles.Conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author JOSE
 */
public class Login extends javax.swing.JFrame {


    /**
     * Creates new form Login
     */
    
    
    // Este puto y capuño constructor me esta dando problema pero lo voy a resolver de inmedianteo
//   public Login(){
//        initComponents();
//        this.setLocationRelativeTo(null);
//    }
    
 //private final Formulario Inicio;  
    
    // Esta linea de codigo representa el metodo constructor a usar
   
//    public Login (Formulario form){
//        this.Inicio = form;
//        initComponents();
//        for(int i = 0; i < 100; i++){
//            if (i == 0){
//                setjpb(i, "Cargando Componetes del sistema...");
//            }
//            else if (i == 20){
//                setjpb(i, "Conectandose a la base de datos...");
//            }
//            else if (i == 40){
//                setjpb(i, "Cargando los modulos del sistema...");
//            }
//            
//            else if (i == 60){
//                setjpb(i, "Cargando las Interfaces de Usuario..");
//            }
//            
//            else if (i == 80){
//                setjpb(i, "Interfaces de usuario cargada correctamente...");
//            }
//            
//            else if (i == 99){
//                setjpb(i, "Carga compleata correctamente...");
//            }
//            
//            else{
//               setjpb(i, "Cargando..."); 
//            }
//            
//            
//        }
//        this.setLocationRelativeTo(null);
//        
//    }

    
    // Este es el metodo set para el jProgressaBar
    
    
//    private void setjpb(int progreso, String informacion){
//        Inicio.getlbl().setText(informacion);
//        Inicio.getjpb().setValue(progreso);
//        
//        try{
//            Thread.sleep(1000);
//            
//        }catch(InterruptedException ex){
//            JOptionPane.showMessageDialog(null, "No se pudo ejecutar la aplicacion");
//        }
//    }
    
    private Connection cn;
    
    private String nombre;
    private String clave;
    private int validar() throws ClassNotFoundException, SQLException{
        this.nombre = txtnombre.getText();
        this.clave = txtclave.getText();
        
        int resultado = 0;
        try{
            String sql = "select * from dbflores where nombre ='" + nombre +"' and clave ='"+clave+"'";
            cn = Conexion.conectar();
            Statement estado = cn.createStatement();
            ResultSet resul = estado.executeQuery(sql);
            
            if (resul.next()){
                resultado = 1;
                JOptionPane.showMessageDialog(null, "todo anda bien");
            }
               
        }catch(SQLException | ClassNotFoundException ex){
            ex.printStackTrace();
        }
        return resultado;
        
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtclave = new javax.swing.JPasswordField();
        txtnombre = new javax.swing.JTextField();
        txtcancelar = new javax.swing.JButton();
        txtingresar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(txtclave);
        txtclave.setBounds(80, 230, 240, 29);

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        getContentPane().add(txtnombre);
        txtnombre.setBounds(80, 180, 240, 28);

        txtcancelar.setText("Cancelar");
        txtcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcancelarActionPerformed(evt);
            }
        });
        getContentPane().add(txtcancelar);
        txtcancelar.setBounds(210, 300, 127, 34);

        txtingresar.setText("Ingresar");
        txtingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtingresarActionPerformed(evt);
            }
        });
        getContentPane().add(txtingresar);
        txtingresar.setBounds(60, 300, 127, 34);

        jLabel1.setText("Usuario");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 160, 36, 14);

        jLabel2.setText("Contraseña");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 210, 56, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_txtcancelarActionPerformed

    private void txtingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtingresarActionPerformed
       JOptionPane.showMessageDialog(null, "el esta adentro y funciona");
        try {
            // TODO add your handling code here:
            
            if (validar() == 1){
                this.dispose();
                JOptionPane.showMessageDialog(null, "Bienvenido\n Has ingresado "
                + "satisfactoriamente al sistema mas completo del mercado", "Mensaje de bienvenida",
                JOptionPane.INFORMATION_MESSAGE);
                
                Formulario frm = new Formulario();
                frm.setVisible(true);
                
            }
            else{
                JOptionPane.showMessageDialog(null, "Error: Usuario o Contrasenia incorrecto");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtingresarActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton txtcancelar;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JButton txtingresar;
    private javax.swing.JTextField txtnombre;
    // End of variables declaration//GEN-END:variables
}
